### PR TITLE
Test OpenSSL::Random is present properly

### PR DESCRIPTION
**Pull request by pitr-ch**

### CODE REVIEW

**Comment by YorickPeterse** [comment]
What's the reason for this change?

**Comment by pitr-ch** [comment]
The old test was always true since there is `::Random`
```
[2] pry(main)> class A; end
=> nil
[3] pry(main)> defined? A::Random
=> "constant"
```

**Comment by YorickPeterse** [comment]
Is it then not better to use `if OpenSSL.const_defined?(:Random)`?

**Comment by pitr-ch** [comment]
yeah it is, updated.

**Comment by pitr-ch** [comment]
It turns out it's our bug. I should have tried it with module not class in the example. Closing.

**Comment by pitr-ch** [comment]
Thanks @YorickPeterse for reply.

**Pull request closed without merging**
